format_version: 10
pipelines:
  mysql:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/raghudevopsb79/expense-ansible
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:GJpOsKchZolqf2Gylrqymw==:48C77QmHmE7ihFUNFmoXRw=="
    stages:
    - DEV:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -i
                - mysql-dev.rdevopsb79.online,
                - -e
                - ansible_user=ec2-user
                - -e
                - ansible_password=${SSH_PASSWORD}
                - -e
                - env=dev
                - -e
                - role_name=mysql
                - expense.yml
                command: ansible-playbook

    - QA:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -l
                command: ls
                run_if: passed

    - STAGE:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -l
                command: ls
                run_if: passed

    - PROD:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -i
                - mysql-prod.rdevopsb79.online,
                - -e
                - ansible_user=ec2-user
                - -e
                - ansible_password=DevOps321
                - -e
                - env=prod
                - -e
                - role_name=mysql
                - expense.yml
                command: ansible-playbook
                run_if: passed
