format_version: 10
pipelines:
  mysql:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/raghudevopsb79/expense-ansible
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:GJpOsKchZolqf2Gylrqymw==:48C77QmHmE7ihFUNFmoXRw=="
      vault_token: "AES:Ro4nPk9BFkts9PbZ7hR+TQ==:3orYTpuPUkzlbp868dzSkAmVr6hMmCztFWPZx/CwdL8="
    environment_variables:
      component: mysql
    template: ansible-app-deployment

